[package]

name = "raisin"
version = "0.0.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[lib]
name = "raisin"
path = "src/lib.rs"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"

[dependencies.anymap]
git = "https://github.com/chris-morgan/anymap.git"

[dependencies.error]
#git = "https://github.com/reem/rust-error.git"
path = "../../out/rust-error"

[dependencies.valico]
path = "../valico"

[dependencies.query]
path = "../rust-query"
