[package]

name = "rustless"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[lib]
name = "rustless"
path = "src/lib.rs"

[[test]]
name = "tests"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"

[dependencies.anymap]
git = "https://github.com/chris-morgan/anymap.git"

[dependencies.error]
git = "https://github.com/reem/rust-error.git"

[dependencies.valico]
git = "https://github.com/rustless/valico.git"

[dependencies.queryst]
git = "https://github.com/rustless/queryst.git"

[dependencies.cookie]
git = "https://github.com/alexcrichton/cookie-rs"

[dependencies.jsonway]
git = "https://github.com/rustless/jsonway"