[package]

name = "rustless"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[lib]
name = "rustless"
path = "src/lib.rs"

[[test]]
name = "tests"

[dependencies]
valico = "*"
queryst = "*"
jsonway = "*"
url = "*"
error = "*"
cookie = "*"
hyper = "*"
iron = "*"