[package]

name = "rustless"
version = "0.0.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[lib]
name = "rustless"
path = "src/lib.rs"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
#path = "../../out/hyper"

[dependencies.url]
git = "https://github.com/servo/rust-url.git"

[dependencies.anymap]
git = "https://github.com/chris-morgan/anymap.git"

[dependencies.error]
git = "https://github.com/reem/rust-error.git"

[dependencies.valico]
git = "https://github.com/rustless/valico.git"
#path = "../valico"

[dependencies.query]
git = "https://github.com/rustless/rust-query.git"
#path = "../rust-query"

[dependencies.cookie]
git = "https://github.com/alexcrichton/cookie-rs"