[package]

name = "rustless"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[lib]
name = "rustless"
path = "src/lib.rs"

[[test]]
name = "tests"

[dependencies]
valico = "~0.1.0"
queryst = "~0.1.0"
jsonway = "~0.1.0"
url = "~0.2.0"
anymap = "~0.9.1"
error = "~0.0.1"
cookie = "~0.0.1"
hyper = "~0.0.1"